-- ========================================================
-- SCHEMA ORACLE DATABASE / ORACLE APEX
-- SISTEMA DE GESTÃO DO INVENTÁRIO ANUAL - SENAPPEN
-- ========================================================

-- 1. TABELA DE UNIDADES GESTORAS (UG)
CREATE TABLE tb_ug (
    id_ug NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo_ug NUMBER(6) NOT NULL UNIQUE,
    sigla_ug VARCHAR2(20) NOT NULL,
    nome_ug VARCHAR2(150) NOT NULL,
    tipo_ug VARCHAR2(30) NOT NULL CHECK (tipo_ug IN ('DIRETORIA', 'PENITENCIARIA_FEDERAL')),
    processo_sei_ug VARCHAR2(40),
    portaria_geral VARCHAR2(200),
    criado_em DATE DEFAULT SYSDATE
);

-- 2. TABELA DE CICLOS DE INVENTÁRIO
CREATE TABLE tb_ciclo_inventario (
    id_ciclo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ano_exercicio NUMBER(4) NOT NULL UNIQUE,
    processo_sei_mae VARCHAR2(40),
    data_limite_cautela DATE,
    data_limite_final DATE,
    status_ciclo VARCHAR2(20) DEFAULT 'EM_ANDAMENTO' CHECK (status_ciclo IN ('PLANEJAMENTO', 'EM_ANDAMENTO', 'HOMOLOGADO', 'ENCERRADO')),
    descricao VARCHAR2(300)
);

-- 3. TABELA DE UNIDADES ORGANIZACIONAIS (UORG)
CREATE TABLE tb_uorg (
    id_uorg NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_ug NUMBER NOT NULL REFERENCES tb_ug(id_ug),
    codigo_uorg VARCHAR2(20) NOT NULL,
    sigla_uorg VARCHAR2(50) NOT NULL,
    nome_uorg VARCHAR2(150),
    ativo VARCHAR2(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    CONSTRAINT unq_ug_uorg UNIQUE (id_ug, codigo_uorg, sigla_uorg)
);

-- 4. TABELA FATO: ACOMPANHAMENTO DO INVENTÁRIO POR UORG
CREATE TABLE tb_inventario_acompanhamento (
    id_acompanhamento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_ciclo NUMBER NOT NULL REFERENCES tb_ciclo_inventario(id_ciclo),
    id_uorg NUMBER NOT NULL REFERENCES tb_uorg(id_uorg),
    sequencia NUMBER(4),
    comissao_designacao VARCHAR2(1000),
    processo_sei_numero VARCHAR2(40),
    processo_sei_link VARCHAR2(1000),
    bens_acautelados_doc VARCHAR2(500),
    bens_acautelados_link VARCHAR2(1000),
    relatorios_sgp VARCHAR2(100),
    relatorio_uorg VARCHAR2(100),
    relatorio_final_ug VARCHAR2(100),
    status_fase VARCHAR2(30) DEFAULT 'PENDENTE_INICIAL' CHECK (status_fase IN ('PENDENTE_INICIAL', 'PROCESSO_AUTUADO', 'CAUTELA_INFORMADA', 'EM_RELATORIO', 'CONCLUIDO')),
    observacao VARCHAR2(2000),
    atualizado_em DATE DEFAULT SYSDATE
);

-- 5. TABELA DE MEMBROS DAS COMISSÕES
CREATE TABLE tb_comissao_membro (
    id_membro NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_ug NUMBER NOT NULL REFERENCES tb_ug(id_ug),
    id_uorg NUMBER REFERENCES tb_uorg(id_uorg),
    nome_servidor VARCHAR2(150) NOT NULL,
    matricula_siape VARCHAR2(20),
    papel_funcao VARCHAR2(50) DEFAULT 'MEMBRO',
    ato_designacao VARCHAR2(200),
    link_ato VARCHAR2(1000)
);

-- 6. TABELA DE CAPACITAÇÃO
CREATE TABLE tb_capacitacao (
    id_capacitacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_ug NUMBER REFERENCES tb_ug(id_ug),
    nome_unidade VARCHAR2(150),
    nome_servidor VARCHAR2(150) NOT NULL,
    observacao_oficio VARCHAR2(300)
);

-- 7. VIEW ANALÍTICA PARA ORACLE APEX
CREATE OR REPLACE VIEW vw_dashboard_inventario AS
SELECT 
    a.id_acompanhamento,
    c.ano_exercicio,
    u.id_ug,
    u.codigo_ug,
    u.sigla_ug,
    u.nome_ug,
    u.tipo_ug,
    o.codigo_uorg,
    o.sigla_uorg,
    a.sequencia,
    a.processo_sei_numero,
    a.processo_sei_link,
    a.bens_acautelados_doc,
    a.bens_acautelados_link,
    a.relatorios_sgp,
    a.relatorio_uorg,
    a.relatorio_final_ug,
    a.status_fase,
    CASE 
        WHEN a.status_fase = 'CONCLUIDO' THEN 100
        WHEN a.status_fase = 'EM_RELATORIO' THEN 75
        WHEN a.status_fase = 'CAUTELA_INFORMADA' THEN 50
        WHEN a.status_fase = 'PROCESSO_AUTUADO' THEN 25
        ELSE 10
    END AS pct_progresso,
    c.data_limite_cautela,
    c.data_limite_final,
    CASE 
        WHEN a.bens_acautelados_doc IS NULL AND SYSDATE > c.data_limite_cautela THEN 'ATRASADO_CAUTELA'
        WHEN a.relatorio_final_ug IS NULL AND SYSDATE > c.data_limite_final THEN 'ATRASADO_FINAL'
        ELSE 'EM_DIA'
    END AS situacao_prazo
FROM tb_inventario_acompanhamento a
JOIN tb_uorg o ON a.id_uorg = o.id_uorg
JOIN tb_ug u ON o.id_ug = u.id_ug
JOIN tb_ciclo_inventario c ON a.id_ciclo = c.id_ciclo;

-- ========================================================
-- SEEDS INICIAIS (EXEMPLOS DML)
-- ========================================================
INSERT INTO tb_ciclo_inventario (id_ciclo, ano_exercicio, processo_sei_mae, data_limite_cautela, data_limite_final, status_ciclo, descricao)
VALUES (1, 2026, '08016.007081/2026-59', TO_DATE('2026-08-31', 'YYYY-MM-DD'), TO_DATE('2026-11-30', 'YYYY-MM-DD'), 'EM_ANDAMENTO', 'Inventário Anual Ordinário dos Bens Patrimoniais Senappen 2026');

INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (1, 200326, 'DIREX', 'DIRETORIA EXECUTIVA', 'DIRETORIA', NULL, NULL);
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (2, 200323, 'DPPF', 'DIRETORIA DE POLÍTICA PENAL FEDERAL', 'DIRETORIA', '08016.015646/2026-71', 'Despacho 3662 (36191712)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (3, 200324, 'DIRPP', 'DIRETORIA DE POLÍTICAS PENITENCIÁRIAS', 'DIRETORIA', NULL, 'Despacho 3716 (36484471)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (4, 200327, 'DIPEN', 'DIRETORIA DE INTELIGÊNCIA PENITENCIÁRIA', 'DIRETORIA', NULL, NULL);
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (5, 200456, 'DICAP', 'DIRETORIA DE CIDADANIA E ALTERNATIVAS PENAIS', 'DIRETORIA', '08016.015872/2026-52', 'Despacho 2490 (36223813)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (6, 200600, 'PFCG', 'PENITENCIÁRIA FEDERAL EM CAMPO GRANDE', 'PENITENCIARIA_FEDERAL', '08118.003298/2026-41', 'Portaria 255 (SEI nº 36185723) e Errata (SEI nº 36320213)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (7, 200601, 'PFCAT', 'PENITENCIÁRIA FEDERAL EM CATANDUVAS', 'PENITENCIARIA_FEDERAL', '08117.003739/2026-15', 'Portaria 135 (SEI nº 36373976)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (8, 200603, 'PFPV', 'PENITENCIÁRIA FEDERAL EM PORTO VELHO', 'PENITENCIARIA_FEDERAL', '08120.005817/2026-67', 'Portaria 244 (36416225)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (9, 200602, 'PFMOS', 'PENITENCIÁRIA FEDERAL EM MOSSORÓ', 'PENITENCIARIA_FEDERAL', '08119.003612/2026-86', 'Portaria 175 (36416194)');
INSERT INTO tb_ug (id_ug, codigo_ug, sigla_ug, nome_ug, tipo_ug, processo_sei_ug, portaria_geral) VALUES (10, 200604, 'PFBRA', 'PENITENCIÁRIA FEDERAL EM BRASÍLIA', 'PENITENCIARIA_FEDERAL', '08016.015704/2026-67', 'Portaria 211 (36385472)');
COMMIT;
